tm = custom_target('tm',
  output: 'aws-'+meson.project_version()+'.tm',
  input:  files(
    meson.project_source_root() / 'aws.tcl',
    meson.project_source_root() / 'build.tcl',
  ),
  env: {
    'TCLLIBPATH':                                   ' '.join(dep_builddirs_trad),
    'TCL'+tclver_major+'_'+tclver_minor+'_TM_PATH': ':'.join(dep_builddirs_tm),
  },
  command: [
    tclsh,
    meson.project_source_root() / 'build.tcl',
    '-' + get_option('tm_mode'),
    '-ver',         meson.project_version(),
    '-source',      meson.project_source_root(),
    '-definitions', meson.project_source_root() / 'botocore/botocore/data',
    '-prefix',      meson.current_build_dir(),
  ],
  depends:  dep_targets,
  build_by_default: true,
  install:          true,
  install_dir:      tcl_dep.get_variable('libdir') / 'tcl' + tclver_major / 'site-tcl',
  install_tag:      meson.is_subproject() ? 'deps' : 'runtime',
)
